name: ci

on: [push, pull_request]

env:
  TF_PLUGIN_DOCS_VERSION: 0.19.4

jobs:
  check-docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - name: Check docs up to date
        run: |
          cd /tmp
          curl -L https://github.com/hashicorp/terraform-plugin-docs/releases/download/v${TF_PLUGIN_DOCS_VERSION}/tfplugindocs_${TF_PLUGIN_DOCS_VERSION}_linux_amd64.zip -o f.zip && unzip ./f.zip && chmod a+x tfplugindocs && sudo mv ./tfplugindocs /usr/local/bin/
          cd -

          ./scripts/check-docs-dirty.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    # Execute the checks inside the container instead the VM.
    container: golangci/golangci-lint:v1.61.0-alpine
    steps:
      - uses: actions/checkout@v4
      - run: |
          export GOFLAGS="-buildvcs=false"
          ./scripts/lint.sh

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: make test

  acceptance-test:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.0.*"
          - "1.1.*"
          - "1.2.*"
          - "1.3.*"
          - "1.4.*"
          - "1.5.*"
          - "1.6.*"
          - "1.7.*"
          - "1.8.*"
          - "1.9.*"
          - "latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: make testacc
